---
title: "Untitled"
author: "Brianna Lawton"
date: "March 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}

library(tidyverse)
library(purrr)
library(sf)
ozbig <- read_sf("./data/gadm36_AU_shp/gadm36_AUS_1.shp")
oz_st <- maptools::thinnedSpatialPoly(as(ozbig, "Spatial"), tolerance = 0.1, minarea = 0.001, topologyPreserve = TRUE)
oz <- st_as_sf(oz_st)

```

## Team 5 Original Function

```{r}
# 
# Mat2Df <- function(Mat){
#   long <- Mat[,1]
#   lat <- Mat[,2]
#   order <- 1:nrow(Mat)
#   group <- rep(rnorm(1),nrow(Mat))
#   df <- data.frame(long=long,lat=lat,group=group,order=order)
#   df
# }
# oz_flatten <- flatten(flatten(oz$geometry))
# ozplus <- purrr::map_df(.x=oz_flatten,.f=Mat2Df)
# #ozplus %>% ggplot(aes(x=long, y=lat, group=group)) + 
# #  geom_polygon()

```

## Team 5 Function BL Function Update

```{r}
team_5 <- function(file="data/gadm36_AU_shp/gadm36_AUS_1.shp", tolerance = 0.1) {
  
   # invalid arguement of file
  if (!file.exists(file)) {
    warning("file does not exist")
    return(NA)
  }
  # invalid arguement of tolerance
  if (!is.numeric(tolerance)) {
    warning("tolerance is not numeric")
    return(NA)
  }
  
  ozbig <- read_sf(file)
  oz_st <- maptools::thinnedSpatialPoly(
    as(ozbig, "Spatial"), tolerance = tolerance, 
    minarea = 0.001, topologyPreserve = TRUE)
  oz <- st_as_sf(oz_st)
  
  Mat2Df <- function(Mat){
  long <- Mat[,1]
  lat <- Mat[,2]
  order <- 1:nrow(Mat)
  group <- rep(rnorm(1),nrow(Mat))
  df <- data.frame(long=long,lat=lat,group=group,order=order)
  df
}
oz_flatten <- flatten(flatten(oz$geometry))
ozplus <- purrr::map_df(.x=oz_flatten,.f=Mat2Df)

return(ozplus)
}

Mat2Df_v <- team_5(file = "./data/gadm36_AU_shp/gadm36_AUS_1.shp", tolerance = 0.1)

Mat2Df_v %>% ggplot(aes(x=long, y=lat, group=group)) + geom_polygon()

```

























##Team 1 original

```{r}
df.oz.purr <- oz$geometry %>%
  map_depth(3, data.frame) %>%
  purrr::flatten() %>%
  purrr::flatten() %>%
  bind_rows(.id = "group") %>%
  rename("lat" = y, "long" = x)
# df.oz.purr %>% 
#   ggplot(aes(x = long, y = lat, group = group)) + 
#     geom_polygon()


```

## Team 1 updated

```{r}
team_1 <- function(file="data/gadm36_AUS_shp/gadm36_AUS_1.shp", tolerance = 0.1) {
  ozbig <- read_sf(file)
  oz_st <- maptools::thinnedSpatialPoly(
    as(ozbig, "Spatial"), tolerance = tolerance, 
    minarea = 0.001, topologyPreserve = TRUE)
  oz <- st_as_sf(oz_st)

  df.oz.purr <- oz$geometry %>% 
    map_depth(3, data.frame) %>%
    purrr::flatten() %>%
    purrr::flatten() %>%
    bind_rows(.id = "group") %>%
    rename("lat" = y, "long" = x)
  
  return(df.oz.purr)
}

df.oz.purr.chn <- team_1(file = "data/gadm36_CHN_shp/gadm36_CHN_1.shp", tolerance = 0.1)

```
